import { VALIDATION_LAYERS } from "./validation-catalog.js";
import { VALIDATION_CONTRACT_SCHEMA_VERSION } from "./validation-contract.js";

/**
 * Portable schema for the immutable validation-contract payload. Runtime
 * admission applies the same closed-world shape plus catalog-backed semantic
 * checks; consumers may persist this object as the v1 interchange schema.
 */
export const VALIDATION_CONTRACT_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://cormidia.dev/schemas/validation-contract/v1.json",
  title: "Cormidia validation contract v1",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "contractId",
    "version",
    "predecessor",
    "app",
    "catalogRef",
    "roadmapRef",
    "unitId",
    "unitMembershipHash",
    "templateRef",
    "affected",
    "acceptanceCriteria",
    "requiresHarnessRevision",
    "harnessRevisionReason",
    "sharedBoundaryDetectorRefs",
    "obligations",
    "requiredGates",
    "proposedAt",
    "acceptedAt",
  ],
  properties: {
    schemaVersion: { const: VALIDATION_CONTRACT_SCHEMA_VERSION },
    contractId: { type: "string", pattern: "^[a-z0-9][a-z0-9._-]{0,127}$" },
    version: { type: "integer", minimum: 1 },
    predecessor: { anyOf: [{ type: "null" }, { $ref: "#/$defs/validationContractRef" }] },
    app: { type: "string", minLength: 1 },
    catalogRef: { $ref: "#/$defs/validationCatalogRef" },
    roadmapRef: { $ref: "#/$defs/roadmapRef" },
    unitId: { type: "string", pattern: "^[a-z0-9][a-z0-9._-]{0,127}$" },
    unitMembershipHash: { $ref: "#/$defs/hash" },
    templateRef: { anyOf: [{ type: "null" }, { $ref: "#/$defs/templateRef" }] },
    affected: { $ref: "#/$defs/affected" },
    acceptanceCriteria: { $ref: "#/$defs/nonEmptyUniqueStrings" },
    requiresHarnessRevision: { type: "boolean" },
    harnessRevisionReason: { type: ["string", "null"] },
    sharedBoundaryDetectorRefs: {
      type: "array",
      items: { $ref: "#/$defs/sharedDetectorRef" },
    },
    obligations: {
      type: "array",
      minItems: 1,
      items: { $ref: "#/$defs/obligation" },
    },
    requiredGates: { $ref: "#/$defs/nonEmptyUniqueStrings" },
    proposedAt: { type: "string", format: "date-time" },
    acceptedAt: { type: "string", format: "date-time" },
  },
  $defs: {
    hash: { type: "string", pattern: "^[a-f0-9]{64}$" },
    machineId: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9._*:/-]{0,255}$" },
    nonEmptyUniqueStrings: {
      type: "array",
      minItems: 1,
      uniqueItems: true,
      items: { type: "string", minLength: 1 },
    },
    stringSet: {
      type: "array",
      uniqueItems: true,
      items: { $ref: "#/$defs/machineId" },
    },
    authorityRef: {
      type: "object",
      additionalProperties: false,
      required: ["kind", "id", "version", "sha256"],
      properties: {
        kind: { type: "string" },
        id: { type: "string", minLength: 1 },
        version: { type: "integer", minimum: 1 },
        sha256: { $ref: "#/$defs/hash" },
      },
    },
    validationContractRef: {
      allOf: [{ $ref: "#/$defs/authorityRef" }, { properties: { kind: { const: "validation_contract" } } }],
    },
    validationCatalogRef: {
      allOf: [{ $ref: "#/$defs/authorityRef" }, { properties: { kind: { const: "validation_catalog" } } }],
    },
    roadmapRef: {
      allOf: [{ $ref: "#/$defs/authorityRef" }, { properties: { kind: { const: "roadmap_plan" } } }],
    },
    templateRef: {
      type: "object",
      additionalProperties: false,
      required: ["templateId", "version"],
      properties: {
        templateId: { $ref: "#/$defs/machineId" },
        version: { type: "integer", minimum: 1 },
      },
    },
    affected: {
      type: "object",
      additionalProperties: false,
      required: [
        "journeyIds",
        "boundaryIds",
        "contractIds",
        "invariantIds",
        "interfaceIds",
        "stateOwnerIds",
        "controlPointIds",
      ],
      properties: {
        journeyIds: { $ref: "#/$defs/stringSet" },
        boundaryIds: { $ref: "#/$defs/stringSet" },
        contractIds: { $ref: "#/$defs/stringSet" },
        invariantIds: { $ref: "#/$defs/stringSet" },
        interfaceIds: { $ref: "#/$defs/stringSet" },
        stateOwnerIds: { $ref: "#/$defs/stringSet" },
        controlPointIds: { $ref: "#/$defs/stringSet" },
      },
    },
    waiver: {
      type: "object",
      additionalProperties: false,
      required: [
        "waiverId",
        "policyClassId",
        "obligationId",
        "unitId",
        "contractId",
        "contractVersion",
        "reason",
        "provenance",
        "expiresAt",
      ],
      properties: {
        waiverId: { $ref: "#/$defs/machineId" },
        policyClassId: { $ref: "#/$defs/machineId" },
        obligationId: { $ref: "#/$defs/machineId" },
        unitId: { type: "string", minLength: 1 },
        contractId: { type: "string", minLength: 1 },
        contractVersion: { type: "integer", minimum: 1 },
        reason: { type: "string", minLength: 1 },
        provenance: {
          type: "object",
          additionalProperties: false,
          required: ["actorId", "authorityRef", "decidedAt"],
          properties: {
            actorId: { type: "string", minLength: 1 },
            authorityRef: { type: "string", minLength: 1 },
            decidedAt: { type: "string", format: "date-time" },
          },
        },
        expiresAt: { type: "string", format: "date-time" },
      },
    },
    obligation: {
      type: "object",
      additionalProperties: false,
      required: [
        "obligationId",
        "caseId",
        "covers",
        "cheapestFalsifyingLayer",
        "failureCases",
        "detectorId",
        "negativeControlId",
        "expectedEvidence",
        "waiver",
      ],
      properties: {
        obligationId: { $ref: "#/$defs/machineId" },
        caseId: { $ref: "#/$defs/machineId" },
        covers: { $ref: "#/$defs/affected" },
        cheapestFalsifyingLayer: { enum: VALIDATION_LAYERS },
        failureCases: { $ref: "#/$defs/nonEmptyUniqueStrings" },
        detectorId: { type: "string", minLength: 1 },
        negativeControlId: { type: "string", minLength: 1 },
        expectedEvidence: { $ref: "#/$defs/nonEmptyUniqueStrings" },
        waiver: { anyOf: [{ type: "null" }, { $ref: "#/$defs/waiver" }] },
      },
    },
    sharedDetectorRef: {
      type: "object",
      additionalProperties: false,
      required: ["boundaryId", "caseId", "detectorId"],
      properties: {
        boundaryId: { $ref: "#/$defs/machineId" },
        caseId: { $ref: "#/$defs/machineId" },
        detectorId: { type: "string", minLength: 1 },
      },
    },
  },
} as const;
