import { existsSync } from "node:fs";
import { lstat, readFile } from "node:fs/promises";
import { join } from "node:path";

export const PRODUCT_DOC_PATHS = ["docs/VISION.md", "docs/REQUIREMENTS.md", "docs/ARCHITECTURE.md"] as const;

interface ScaffoldDocument {
  path: string;
  content: string;
}

interface LegacyScaffold {
  kind: "recognized";
  template: "typescript-node" | "bare";
  documents: ScaffoldDocument[];
}

export type LegacyScaffoldDiscovery = LegacyScaffold | { kind: "none" } | { kind: "unresolved"; reason: string };

export function renderProductDocScaffoldDocuments(
  appName: string,
  goal: string,
  template: "typescript-node" | "bare",
): ScaffoldDocument[] {
  return [
    { path: PRODUCT_DOC_PATHS[0], content: visionMd(appName, goal) },
    {
      path: PRODUCT_DOC_PATHS[1],
      content: template === "bare" ? bareRequirementsMd(appName, goal) : requirementsMd(appName, goal),
    },
    {
      path: PRODUCT_DOC_PATHS[2],
      content: template === "bare" ? bareArchitectureMd(appName) : architectureMd(appName),
    },
  ];
}

export async function discoverLegacyProductDocScaffold(
  root: string,
  appName: string,
): Promise<LegacyScaffoldDiscovery> {
  const seedPath = join(root, ".cormidia/planning/0001-greenfield-seed.md");
  if (!existsSync(seedPath)) {
    return existsSync(join(root, ".cormidia/bootstrap/initial-issue.md"))
      ? { kind: "unresolved", reason: "the legacy planning seed is missing" }
      : { kind: "none" };
  }
  if ((await lstat(seedPath)).isSymbolicLink()) {
    return { kind: "unresolved", reason: "the legacy planning seed is a symbolic link" };
  }
  const seed = await readFile(seedPath, "utf8");
  for (const template of ["typescript-node", "bare"] as const) {
    const goal = parseLegacyGoal(seed, appName, template);
    if (goal !== undefined && seed === legacyPlanningSeed(appName, goal, template)) {
      return { kind: "recognized", template, documents: renderProductDocScaffoldDocuments(appName, goal, template) };
    }
  }
  return { kind: "unresolved", reason: "the legacy planning seed no longer matches generated bytes" };
}

function parseLegacyGoal(seed: string, appName: string, template: "typescript-node" | "bare"): string | undefined {
  const prefix = `# Greenfield Planning Seed - ${appName}\n\n## Product Goal\n\n`;
  if (!seed.startsWith(prefix)) return undefined;
  const delimiter = template === "bare" ? "\n\n## Template Boundary\n" : "\n\n## Planner Task\n";
  const end = seed.indexOf(delimiter, prefix.length);
  if (end < 0) return undefined;
  const goal = seed.slice(prefix.length, end);
  return goal.trim().length > 0 ? goal : undefined;
}

function legacyPlanningSeed(appName: string, goal: string, template: "typescript-node" | "bare"): string {
  if (template === "bare") {
    return `# Greenfield Planning Seed - ${appName}

## Product Goal

${goal}

## Template Boundary

The operator explicitly selected the stack-neutral \`bare\` template. The
scaffold emitted no application/runtime skeleton and did not infer a stack from
the free-form goal.

## Planner Task

Refine docs/VISION.md and docs/REQUIREMENTS.md into a buildable first milestone.
The first implementation dependency must explicitly select and document the
stack, add real source and local workflows, and establish meaningful
stack-specific test and lint gates in \`.cormidia/config.yaml\`.

## Decomposition Guidance

- Start with a product-definition ticket only if the current PRD is too vague.
- Keep stack selection, the first observable slice, and non-vacuous gate setup
  together or encode explicit dependencies that prevent implementation from
  being certified before its gates exist.
- Add infrastructure tickets only when the first slice needs them.
- Keep Support and Marketing work tied to declared channels and real artifacts.
`;
  }
  return `# Greenfield Planning Seed - ${appName}

## Product Goal

${goal}

## Planner Task

Refine docs/VISION.md and docs/REQUIREMENTS.md into a buildable first milestone.
Prefer concrete GitHub issues with binary acceptance criteria and named tests.

## Decomposition Guidance

- Start with a product-definition ticket only if the current PRD is too vague.
- Next create one first-slice implementation ticket.
- Add infrastructure tickets only when the first slice needs them.
- Keep Support and Marketing work tied to declared channels and real artifacts.
`;
}

function visionMd(appName: string, goal: string): string {
  return `# Vision - ${appName}

## Goal

${goal}

## Audience

- Primary users who need the core workflow completed with low friction.
- Operators who need clear status, support inputs, and release notes.
- The Cormidia agent team that will convert this seed into reviewed tickets.

## First Outcome

The first milestone should prove one complete product workflow from empty state
to a visible result. Keep scope narrow enough for one Builder PR and make the
acceptance criteria observable through tests or a local manual check.
`;
}

function requirementsMd(appName: string, goal: string): string {
  return `# Requirements - ${appName}

This is a bootstrap PRD seed generated from the initial goal. The Planner should
refine it before deep product work.

## Problem

${goal}

## Initial Requirements

- Define the first persona and the workflow they complete.
- Implement a minimal web UI for the first workflow.
- Persist only the state needed to prove the workflow, or document why the
  first slice is intentionally static.
- Keep \`npm test\` and \`npm run lint\` green.
- Update docs when product behavior changes.

## Acceptance Contract For First Ticket

- AC1: The app renders the product goal and starter work areas.
- AC2: A domain test verifies the product goal and starter backlog.
- AC3: The README explains local setup and Cormidia next steps.
- AC4: Cormidia gate commands are configured in \`.cormidia/config.yaml\`.
`;
}

function bareRequirementsMd(appName: string, goal: string): string {
  return `# Requirements - ${appName}

This is a stack-neutral bootstrap PRD seed generated from the initial goal. The
Planner should refine it before deep product work; \`cormidia new-app\` has not
inferred an implementation stack from the goal.

## Problem

${goal}

## Initial Requirements

- Define the first persona and the workflow they complete.
- Select an implementation stack explicitly and record the decision in
  \`docs/ARCHITECTURE.md\`.
- Implement the smallest observable end-to-end product slice appropriate to
  that stack.
- Add meaningful automated tests and lint or static analysis for the selected
  stack.
- Configure the resulting commands in \`.cormidia/config.yaml\`; a no-op or a
  command that succeeds while running zero tests is not acceptable.
- Update the runbook and this requirements document with the real commands and
  behavior.

## Acceptance Contract For First Implementation

- AC1: The selected stack and its rationale are documented.
- AC2: The repository contains the stack's real manifest, source, and local
  workflow rather than placeholder application files.
- AC3: \`test_command\` runs named behavior tests and fails when that behavior is
  broken.
- AC4: \`lint_command\` performs meaningful lint or static analysis.
- AC5: The first product workflow has an observable result and updated docs.
`;
}

function architectureMd(appName: string): string {
  return `# Architecture - ${appName}

## Current Shape

- Static HTML entry point served locally by \`scripts/server.mjs\`.
- Strict TypeScript domain code in \`src/domain.ts\`.
- Browser rendering in \`src/client.ts\`.
- Node built-in tests in \`test/domain.test.ts\`.

## Evolution

The first Planner pass should decide whether the product needs a backend,
database, auth, queue, or third-party integrations. Add those only when a ticket
has explicit acceptance criteria and matching gates.
`;
}

function bareArchitectureMd(appName: string): string {
  return `# Architecture - ${appName}

## Current Shape

No application stack is selected. The bare template contains product truth and
Cormidia bootstrap artifacts only; it emits no runtime, package-manager,
framework, source, test, or server skeleton.

## First Implementation Decision

Choose a stack from the product requirements and any reviewed design sources,
then record the runtime, package/build tooling, source layout, test strategy,
and local execution path here. The scaffold does not infer that choice from
free-form goal text.

## Quality-Gate Boundary

\`.cormidia/config.yaml\` intentionally has no \`test_command\` or \`lint_command\`.
Cormidia's required gates therefore fail closed until the first implementation
adds meaningful stack-specific commands. Gate commands are top-level keys,
siblings of \`apps\`; never put them under \`apps.<name>\`. Add
\`setup_command\` only when a fresh worktree needs a deterministic setup step.

## Dependency Build Scripts

Cormidia runs every install with dependency build (postinstall) scripts **denied**
by default — a package that silently runs an install script is the more
dangerous default, and pnpm answers an unanswerable build question by writing a
placeholder into \`pnpm-workspace.yaml\` rather than by asking. If a dependency
genuinely needs its install script (a native binary download, for example), opt
in **explicitly and narrowly** in \`setup_command\`: commit the decision as an
\`allowBuilds\` entry and add \`--no-ignore-scripts\` to the install, for example
\`pnpm install --frozen-lockfile --no-ignore-scripts\`. Never answer a
\`set this to true or false\` placeholder by appending a second \`allowBuilds:\`
block — YAML forbids duplicate mapping keys, and the result is a file the
package manager can no longer parse, including on the run that would fix it.
`;
}
